### ISSUE TITLE
🐛 magic accuracy seems off

### ISSUE THREAD

**Issue by twelvedudes** [TabulaRasaXI/TabulaRasa#102] opened 2022-07-12 03:31 UTC
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

Seems like slow para blind ect  were having a hard time landing by both myself and the whm in the party in the dunes
we went from crabs>flys. eventually i just stopped trying and only healed. my enfeebling skill was almost capped and whm's was capped

## Expected behavior

enfeebles to land more often

**Comment by The-Aerec** [comment] 2022-07-12 15:15
Hi could you be more specific on:

Level
Equipment

I did some extended tests in the dunes as a naked 15 rdm with no gear and was landing enfeebling spells with few resists.

![image](https://user-images.githubusercontent.com/6257062/178524773-1afa31b8-f49e-4dc9-ba33-6f329c6bb5c1.png)

**Comment by The-Aerec** [comment] 2022-07-12 15:15
9/10 landed on IT mobs

**Comment by twelvedudes** [comment] 2022-07-13 03:39
under sync that is not happening on tabula it was more like 1/10 landed gear was as follows

![image](https://user-images.githubusercontent.com/108678300/178645523-39d45a6b-d5a5-47aa-975c-8b0b67100c04.png)

**Comment by Killvoid** [comment] 2022-07-13 07:14
Not sure if I can say with confidence that enfeeble rates are "wrong" due to not having capped skill currently.  I would want to cap skills and go test it more.  But I will post some date from my dunes party since it definitely felt a bit on the weak side... to the point of being unreasonable to cast them.

XP camp: Dunes crab/fly
Level: 15-16
Enfeeb skill: ~25
Gear:
![image](https://user-images.githubusercontent.com/109204398/178673042-38c38e2a-c5e1-492a-b693-b6b9e964ea22.png)

paralyze casts: 23
success: 9
resists: 14
success rate: 39%

It's a small sample size and uncapped skill so I would want to test more before declaring it an issue for sure, but since someone make a ticket already I wanted to give my input.

**Comment by 0phie** [comment] 2022-07-13 20:09
Hi there!

So after looking into this issue I see a few things that will definitely make this not work as you intended for landing enfeebles. Based on our magic accuracy formula the MEVA of the mob is determined with a dStat + (dLvl * 4) so on average if you are fighting flies at 15 and most flies are between 19-21 you will on average see a 3-4 dStat plus an additional 16-24 MEVA from the mob's dLvl. Thus you are looking at between 19-28 MEVA on a mob as a whole at that level range. 

In comparison, with the gear you have both showcased, you are still looking at that 3-4 dStat difference between you and the mob first, second you are also looking at the under cap skills against an IT mob. This drastically impacts your ability to land spells simply due to you having on average 10-12 MACC against this mob using our formulas. 

So, when we take into account let's say white magic, these spells full resist if the resist value is less than 0.5, for instance if you got a 1/16th (0.0625) for a resist it would just say resists, but if you got a 2/3rd then you would have it apply at a lower duration. So when you are trying to casts these spells with low MACC and the mob having comparatively high MEVA you are bound to get a lot of resists.

I took both gear setups and tried it at both capped skill and non-capped skill and saw a markedly large difference between the two against a Damselfly with dLvl 6. At 25% I did have roughly a 32% success rate while at capped skill it was closer to 50% with the same gear setup. When I introduced additional MND gear for white magic that rate went up significantly as well. At this point, I see nothing wrong with magic accuracy, rather it is a gearing and skill level problem where you are calculating as a low MACC compared to MEVA. 

Now, you may say that this seems harsh and "why is magic accuracy so bad?!?!?" Well, the answer to that is that the current formulas are based on what is currently known about retail's magic accuracy which was never shown to change in the life of the game. We have someone who has pulled together a whole host of resources regarding this and has reviewed all code written related to it. Back in the day, magic accuracy was a nightmare at low levels, it is just most private servers don't have accurate magic accuracy formulas or when they did get them it was late enough into the server's lifecycle that people had better gear, capped skills, etc. prior to testing. If you have any questions about this, I'd be more than happy to discuss this further, but unless you can provide me with an era source showing conclusive proof that magic accuracy was different at lower levels under similar conditions I will not be personally changing it. 

Now, if the Tabula Rasa staff decides it is necessary to change it they may do so as well, but those on AirSkyBoat will not be changing the formula as it is properly calculating and makes landing magic as difficult as it should be in the game. Since this is working as intended it is not a bug, thus this issue should be closed. Further discussion will have to happen directly with the Tabula staff to determine if they wish to keep our magic accuracy changes (which so far they have approved of).

**Comment by Killvoid** [comment] 2022-07-13 23:31
I trust the numbers you have are accurate.  I will note I had another dunes party again today, similar gear with slightly higher skill 27-28 and saw about the same result... 60-70% resists rates on paralyze.  Contrary to this when casting slow or blind I had 80% success rates.  Might just be an issue specific to flies and their resistance to para specifically? IDK   I understand that at uncapped skill I will see more resists than usual, paralyze just felt abnormally bad.

Thanks for looking into the issue though and appreciate all the time you devs spend on this project!

**Comment by 0phie** [comment] 2022-07-14 00:37
It really is just that with uncapped skill your magic accuracy is that low. Paralyze specifically has a 0.5 resist minimum, so anything less is no effect. It really is just up to chance at that point if you "high roll" on the resist rate which does happen, but it isn't something specific to paralyze.

**Comment by Simseru** [comment] 2022-07-19 05:06
I came here looking around cause I feel like my BLM nukes are getting resisted out the wazoo while leveling. Went down the rabbit whole with the magic.lua instead of the damage_spell.lua since this thread was about that.

Is your statement  `Based on our magic accuracy formula the MEVA of the mob is determined with a dStat + (dLvl * 4) ` accurate? I did some digging and that is not what I was coming up with. MEVA formula for non-nukes using the magic.lua use `magiceva = target:getMod(xi.mod.MEVA) + (4 * dLvl) + resMod + effectRes` so the 4*dlvl is correct but the dstat piece I don't believe to be accurate. `target:getMod(xi.mod.MEVA)` based off what I read, it seems to default to rank3 on all mobs in the mobutils.cpp which should set this for a lvl 20 fly to`58.2 converted to 58 cause integers` using `(uint16)(5 + (lvl - 1) * 2.8f);` So if you are 15 fighting a 20 fly thats 58 + (5 * 4) == 78 MEVA.

The major macc formula in magic.lua seems to be for players `magicacc = caster:getSkillLevel(skillType) + gearBonus + dStatAcc` assuming an A+ in enfeebling is 48 at level 15. `dStat = utils.clamp(dStat, 0, 50) -- Clamp to maximum of 50 dStat` makes me think dStat for enfeebles cannot hurt accuracy it just no longer helps as it cannot go below 0 and therefore will not punish you. So assuming you do not have any MACC gear or food as this lvl 15 rdm in the dunes, you have `48 + 0 + 0 = 48 macc` Then we `calculateMagicHitRate(magicacc[48], magiceva[78], dLvl[5])` We then do `magicAccDiff = magicacc[48] - magiceva[78]` so maccdiff ==-30. Since -30 is < 0 we use `if magicAccDiff < 0 then
        p = utils.clamp(50 + math.floor(magicAccDiff[-30] / 2), 5, 95)` so 50 + -15 = 35. dlvl data hand off to this function seems to serve no purpose.

Is the chance to land an enfeeble as a 15 RDM with capped enfeebling with a mnd deficit or break even due to lack of gear 35%? Based on what im reading, as a 15RDM trying to enfeeble a 20 fly I would need 30 MND over the fly to break even and reach 50% accuracy? So for enfeebles with these calculations you basically need the dstat advantage plus +skill equal to the amount of levels the mob is over you multiplied by the appropriate skill levels for a rank C skill at that level range to make up the difference in macc vs meva. This seems VERY punishing at low/mid levels and maybe even on HNMs that have 20 levels on you. If wyrms at 95 have 352 base MEVA + 100 (5 * 20) thats 452 MEVA. How are you supposed to even dent that gap when player skill caps at 278 A+, you have to compensate 37 via merits/+skillGear/dStat to even reach the 5% acc marker that it will otherwise just clamp to minimum 5% anyway. Doing the MEVA math this way helps me understand what feels like an 80% resist rate on my nukes with +10 INT & capped elemental in Qufim EXP parties even though the nuking formula is a little different(no meva dlvl*4 so less punishing?). Am I missing something?

**Comment by Simseru** [comment] 2022-07-19 06:25
Before I head to bed. Quick maffz.
Assuming that is the correct way to get a mobs MEVA.
Nukes from a 15BLM(48skill) on a 20FLY(58meva)
48 - 15(for level gap >=5) = 33 MACC - 58MEVA == -45.  (50 +(-25/2)) == 37.5. So looking at a 62.5% resist rate for nukes. And that is just for a 5gap which is usually around when camps die.
Nukes from a 15BLM(48skill) on a 23FLY(66.6meva)
48 - 15(for level gap >=5) = 33 MACC - 66 MEVA == -45.  (50 +(-33/2)) == 33.5. So looking at a 66.5% resist rate at 8 lvl gap for the start of exp camp

Getting rid of the -15 macc level penalty might help a bit
48 - 66 == -18 (50 +(-18/2)) == 41. So looking at a 59% resist rate for nukes at 8 lvl gap for the start of exp camp.

Logged into a test server and popped Kirin (92) and as a 99 BLM with capped skills, like 424? chainspell freeze seemed to be at the floored 5% hit rate(didnt see any mid resist casts, was either floor or a full hit), tornado seemed slightly better likely due to the if >.5 roll and mob is weak to ele ResistTier -1 math(a lot more mid resist casts thanks to type advantage).

If these are formulas were extrapolated from current retail, keep in mind current retail offers insane amounts of MACC, stats and +skill on gear to make up for the huge gaps this creates in player vs mob stats. That type of gear stating is not available in era and this seems like it will be insanely hard or impossible to overcome with lvl 75 era gear.

**Comment by The-Aerec** [comment] 2022-07-19 17:16
All the current MACC formulas come from the discussions here:
https://discord.com/channels/966004751244329011/986311863660867604

**Comment by 0phie** [comment] 2022-07-19 17:46
Additionally, in the case of magic accuracy those comments are not representative of how we calculate it now. I did not update them as the calculation for magic accuracy is actually very complex compared to what base LSB had. We at ASB strive for era accuracy more than anything and we have no knowledge of these formulas ever changing. One of the reasons those resist rates feel harsh is also because y'all are at 50 cap right now which in era did make things hard to land. I have tested this at both low levels and post 60 which as you alluded to would have a drastic difference between the two. As of now, if you feel these formulas are "too harsh" for Tabula Rasa please take it up with the server administration staff as these have been proven accurate for the era.

If you are looking to directly check these accuracy formulas please utilize prints throughout the functions, as I did, because the formulation of magic hit rate is actually quite complex and has a lot of functions involved that you have not taken into account. When we talk about magic accuracy we are actually speaking of magic hit rate which takes into account elemental meva, magic eva, magic accuracy, dlvl, and dstat.

**Comment by Simseru** [comment] 2022-07-19 18:36
I don't understand the multiple references to take it up with Tabula devs when this is the tabula rasa git and I am posting this to the tabula rasa git for tabula rasa devs to review, any assistance and insight from ASB or LSB devs is appreciated.

After having a very fun time spamming 10 dmg nukes all day I followed the breadcrumb trails in the lua and found the base MEVA formula in the cpp to calculate what should be the accuracy which I suspected to be very harsh, which supported my terrible player experience. I personally do not think a dismissive, the system is complicated just trust us, is a healthy or constructive response when the server I am reporting this for is openly in a beta phase and everything directly helps the underlying base for future projects.

This was not an attack on peoples character or development ability but an inquiry if my understanding of the current implementation is correct, and if so, I provided feedback as such.

I do not have a dev environment as I am not a dev nor do I have any desire to actively develop at this time. I am simply a player and was offering feedback from a player experience and providing the supporting evidence based on an understanding of the underlying systems being used that would lean towards the 70-80% resist rate I was feeling is systematic and not arbitrary player RNG. 

If this feedback is reviewed, systems tested and an issue is discovered sooner rather than later, great.
If this feedback is reviewed, systems tested and found to be me not knowing everything about all the changes to the base and is working fine, great.
If this feedback is reviewed and discarded, great.

Soloing pet mobs was a standard practice for BLMs. I tried to fight a VT pet leech in qufim 4 lvls above me(25 vs 29) 31+13 INT
Thunder22 > Blizzard81 >Thunder22 > Fire36 > Blizzard9 > Aero7 > Thunder4 >> had to zone it.

**Comment by 0phie** [comment] 2022-07-19 19:27
So in regards to this thread, I was specifically asked by TR staff to take a look at it originally. Since it has only been me and TRs playerbase until Aerec (who is also from ASB) hopped in, I can only speak from an era mechanics perspective. (Hence the reference to take it up with the TR staff) As it is now, I can vouch for the accuracy of magic hit rate as a whole as it is utilizing known formulas for its calculations. As for any customizations to this, is where the TR admins come into play as they would have to be the ones coding it as I will not be including it in ASB nor taking the time to code it personally.

As for your issues, like I said they are primarily exasperated by the fact that you are at a low level cap with what I'd consider minimal gear for the level. We all remember things differently from "era" but unless we have hard data supporting a decision, which in the case of changing magic hit rate we did, these systems pulled directly from ASB may seem harsh as era in general was harsh. I'm not trying to be dismissive in this case, rather just explaining that the code itself is complex, these formulas are complex, and that there is a lot more to take into account besides simple MACC vs MEVA formulation. (Hence the prints in code being required to easily and consistently reproduce the numbers that the game uses)

In this case as I recommended, I would reach out to TR's staff on discord or something as to my knowledge they have stopped checking this thread. Thus it will take some advocacy on the playerbase's part if this is something y'all want changed as TR does strive to be era which in most cases they will pull major mechanics like this directly from ASB. So all I am doing in this thread is gathering the data points y'all have provided, checking them against the formula using the setups each person has had, and ensuring these numbers match what the calculation should be providing.

**Comment by Simseru** [comment] 2022-07-19 20:00
I appreciate your input as there is nothing in this thread indicating to any players, myself included, that TR staff passed the buck to a separate dev team. It just looks like out of the kindness of your hearts you were hoping in trying to help due to interest on the topic.

Personally the other elements to the formula would only further increase the resist rates until you are at a level range where you can start having a positive dint instead of a negative so I would say my numbers are optimistic for the ranges discussed. Which even if what you say is true and the formula works for end game, if my math/assumptions are correct it makes you basically a leech in EXP parties until then, and again off my math/assumptions I don't think it will get much better at end game due to the large level and dlvl the top tier mobs will have. Even on other servers where blackmages consistently landed spells they didnt get invites and had to solo pets or do BLM burns, now having 4 BLMS in a party nuking for 10-20 each means BLMs cant even band together to level in pug alley or ulli room etc (im not talking about BLM AOE burns, that needs to stay dead for eternity imo).

Like I said, I am currently just a player and will continue to simply report things that don't seem right and whether they are investigated or ignored is not up to me as a player.

I am really not looking to spend a great deal of time debating with people so this is probably my last response in this thread as I am sure you have plenty of stuff to do as well. Things like this just change the meta and have to adapt as a player if it stays as-is.

Thanks for being responsive, I hope whether this is researched or not, or changed or not, it ends up how you want your server to perform.

Best of luck.

**Comment by MeyiLekoh** [comment] 2022-07-21 03:11
Is it possible that the formula may calculate differently based on level ranges? Such as combat skills get separated by level 61 (A+ and A- are the same level until 61, then they have their own tiers), could it be that other formulas change too? 

While Dunes sucks, and armor and skill does greatly impact how well you land spells, I can't help but wonder if there was some wiggle room for lower level monsters. 

It's also obnoxious when a capped elemental Taru BLM with INT+ gear casts Stonega II on Shadow Lord and does 6 damage. Content was made for level 50s, albeit challenging, and should be possible to land higher damage on.

**Comment by twelvedudes** [comment] 2022-07-21 10:51
> Is it possible that the formula may calculate differently based on level ranges? Such as combat skills get separated by level 61 (A+ and A- are the same level until 61, then they have their own tiers), could it be that other formulas change too?
> 
> While Dunes sucks, and armor and skill does greatly impact how well you land spells, I can't help but wonder if there was some wiggle room for lower level monsters.
> 
> It's also obnoxious when a capped elemental Taru BLM with INT+ gear casts Stonega II on Shadow Lord and does 6 damage. Content was made for level 50s, albeit challenging, and should be possible to land higher damage on.

Seems like it is also doing this in qufim with decent gear and capped skills today

**Comment by Jimmayus** [comment] 2022-07-24 01:41
This was brought to my attention this evening. I'm the person distilling the information pertaining to magic hit rates and have been lax in finishing detailing some of the more important hit rate modifiers the are most beneficial for lower level players. The fault is entirely my own, there is no way the dev team for this server would have known about this in advance. For reference your Fire spells on Fly-family monsters in this instance would have a 37.5 * 1.3x modifier to hit rate, resulting in a 48.75% unresisted rate, which is extremely fair by FFXI internal mechanics standards. Paralyze has a 1.5x modifier on Fly-type monsters for reference and thus would have an even higher hit rate. 

Their implementation is correct to this point, it is simply incomplete. I am endeavoring to complete the information distillation this evening.

**Closed as completed** 2022-09-05 00:09 UTC
Labels: bug
