### ISSUE TITLE
🐛Worms are recasting too quickly

### ISSUE THREAD

**Issue by PasiXI** [TabulaRasaXI/TabulaRasa#37] opened 2022-07-08 14:27 UTC
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Worms are currently casting too quickly between casts. Within 1-2 delay

## Expected behavior

I can't find any any information on how much time needs to be between. However, I logged into Eden and tested it on a worm in Attowha. After the animation of the casting stopped, the worm would cast after 12-15 seconds.

**Comment by Warp-ass** [comment] 2022-07-08 14:46
is it that way on eden because eden made it that way? if ours are unmodified from the original project then eden must be different somewhere somehow

**Comment by PasiXI** [comment] 2022-07-08 15:16
Eden attempts to be true to Era, so I have to assume it's Era, but it could very much be adjusted to their way they see fit. I only used them as a Reference. Since I could find no other data on it on wiki or googling it.

**Comment by soapytoast** [comment] 2022-07-31 14:17
this will need retail testing to verify likely

**Comment by austinclprojects** [comment] 2022-09-05 21:50
Confirmed they should be casting every ~15-20 seconds.

**Comment by bran-van-d** [comment] 2022-11-30 02:35
I imagine this to be fixed by ASB PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/884

I tested in game for 4 stone casts -- range was 10s, 12s, 22s

**Closed as completed by bran-van-d** 2022-11-30 02:35 UTC
Labels: bug
